version: "3"
services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "30001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: digitalEducation@edu.com
      PGADMIN_DEFAULT_PASSWORD: digitalEducation

  db:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: digital_education
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    restart: always
    volumes:
      - digital-education-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  digital-education-data:

