CREATE TABLE IF NOT EXISTS students (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(50) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,
    first_name varchar(25) NOT NULL,
    last_name varchar(25) NOT NULL,
    active boolean
);

CREATE TABLE IF NOT EXISTS question_form (
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     question text NOT NULL,
     student_id integer REFERENCES students(id)
);

ALTER TABLE question_form
    ADD CONSTRAINT fk_student_question_form
        FOREIGN KEY (student_id)
            REFERENCES students(id);